version: "3"
services: 
    mecab:
        build:
            dockerfile: dockerfiles/mecab/Dockerfile
            context: .
        command: ./scripts/test.sh all "camphr_lang[mecab]"
    juman:
        build:
            dockerfile: dockerfiles/juman/Dockerfile
            context: .
        command: ./scripts/test.sh all "camphr_lang[juman]"
        volumes:
          - .:/app/
    sentencepiece:
        build:
            dockerfile: dockerfiles/Dockerfile.sentencepiece
            context: .
        command: ./scripts/test.sh all "camphr_lang[sentencepiece]"
        volumes:
          - .:/app/
    plain:
        build:
            dockerfile: dockerfiles/Dockerfile
            context: .
        command: ./scripts/test.sh all "camphr_lang[sentencepiece]"
        volumes:
          - .:/app/

