version: "3"
services: 
    test:
        build:
          dockerfile: ./dockerfiles/Dockerfile
          context: .
        command: ./scripts/test.sh all "camphr_core[sentencepiece]"
        volumes:
            - cache:/root/.cache

    mecab:
        build:
            dockerfile: dockerfiles/mecab/Dockerfile
            context: .
        command: make all
        volumes:
          - type: bind
            source: .
            target: /app

    juman:
        build:
            dockerfile: dockerfiles/juman/Dockerfile
            context: .
        command: poetry run pytest tests
        volumes:
          - type: bind
            source: .
            target: /app
volumes:
    cache:

