version: "3"
services: 
    mecab:
        build:
            dockerfile: dockerfiles/Dockerfile.mecab
            context: .
            args:
              PYTHON_VERSION: ${PYTHON_VERSION}
        command: poetry run pytest tests
        volumes:
          - type: bind
            source: .
            target: /app
    juman:
        build:
            dockerfile: dockerfiles/juman/Dockerfile
            context: .
            args:
              PYTHON_VERSION: ${PYTHON_VERSION}
        command: poetry run pytest tests
