[tool.poetry]
name = "camphr_pipelines"
version = "0.1.0"
description = ""
authors = ["Yohei Tamura <tamuhey@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

# TODO
camphr_core = {path = "../camphr_core", develop=true}
camphr_torch = {path = "../camphr_torch", develop=true}
camphr_transformers = {path = "../camphr_transformers", develop=true}
camphr = {path = "../..", develop=true}
dataclass-utils = "^0.7.10"

[tool.poetry.dev-dependencies]
camphr_test = {path = "../camphr_test", develop=true}
pytest = "^6.2.4"
mypy = "^0.812"
flake8 = "^3.9.2"
pyknp = "0.4.2"
mojimoji = "^0.0.11"
mecab-python3 = "^1.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
