name: test and publish

on: 
  push:
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  test:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        include:
          - package: camphr_transformers
            extra: torch
            dockerfile: base
          - package: camphr
            extra: base
            dockerfile: base
          - package: camphr
            extra: mecab
            dockerfile: mecab
          - package: camphr
            extra: juman
            dockerfile: juman
          - package: camphr
            extra: sentencepiece
            dockerfile: sentencepiece
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install fire
      run: python -m pip install -U pip setuptools fire
    - name: Run test
      run: |
        python test_docker.py ${{ matrix.python-version }} \
          --dockerfile-ext ${{ matrix.dockerfile }} \
          --install-cmd "poetry install -E ${{ matrix.extra }}" \
          --package ${{ matrix.package }}


  publish:
      if: github.event_name == 'push' && startsWith(github.event.ref, "refs/tags/${{ matrix.package }}")
      needs: test
      runs-on: ubuntu-latest
      matrix:
        package: ["camphr", "camphr_transformers"]
      steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install publishment tool
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Publish pypi package
        working-directory: packages/${{ matrix.package }}
        run: poetry publish -p '${{ secrets.PYPI_PASS }}' -u '${{ secrets.PYPI_USER }}' --build
