name: test and publish

on: 
  push:
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  test:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest]
        extra: ["base", "mecab", "sentencepiece", "juman"]
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Build image
      run: |
        docker build --build-arg PYTHON_VERSION=${{ matrix.PYTHON_VERSION }} \
          -f dockerfiles/Dockerfile.${{ matrix.extra }} \
          --build-arg INSTALL_CMD="poetry install -E ${{ matrix.extra }}" \
          -t test .
    - name: Run test
      run: docker run test /root/test_local.sh camphr

  publish:
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
      needs: test
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          python-version: [3.7]
          os: [ubuntu-latest]
      steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install publishment tool
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Publish pypi package
        run: poetry publish -p '${{ secrets.PYPI_PASS }}' -u '${{ secrets.PYPI_USER }}' --build
